function gen_gaussj(outDir)
%GEN_GAUSSJ  Golden values for sctool.gaussj(n, alf, bet).

cases = struct('desc', {}, 'inputs', {}, 'outputs', {}, 'tol', {});

specs = { ...
    4,  0,    0,    'n=4  alf=0 bet=0   (Gauss-Legendre)'; ...
    8,  0,    0,    'n=8  alf=0 bet=0   (Gauss-Legendre)'; ...
    8,  0,    0.5,  'n=8  alf=0 bet=0.5 (typical SC corner)'; ...
    8,  0,   -0.5,  'n=8  alf=0 bet=-0.5'; ...
    8,  0,    1.5,  'n=8  alf=0 bet=1.5 (reentrant corner)'; ...
    12, 0,    0.5,  'n=12 alf=0 bet=0.5'; ...
    1,  0,    0,    'n=1  alf=0 bet=0   (edge case)'; ...
    8,  0.5,  0.5,  'n=8  alf=0.5 bet=0.5 (symmetric Jacobi)'; ...
};

for k = 1:size(specs, 1)
    n   = specs{k,1};
    alf = specs{k,2};
    bet = specs{k,3};
    [z, w] = sctool.gaussj(n, alf, bet);
    cases(end+1) = struct( ...
        'desc',    specs{k,4}, ...
        'inputs',  struct('n', n, 'alf', alf, 'bet', bet), ...
        'outputs', struct('z', z, 'w', w), ...
        'tol',     1e-14); %#ok<AGROW>
end

save(fullfile(outDir, 'gaussj.mat'), 'cases');
fprintf('  gaussj: %d cases\n', numel(cases));
end
