function gen_stripmap_class(outDir)
%GEN_STRIPMAP_CLASS  Golden values for the @stripmap class-level methods:
%   eval, evalinv, evaldiff, accuracy.

opt = sctool.scmapopt('trace', 0, 'tol', 1e-12);

stripSpecs = { ...
    polygon([4, 2i, -2+4i, -3, -3-1i, 2-2i]), [1, 4], 'hex6'; ...
    polygon([1i, -1+1i, -1-1i, 1-1i, 1, 0]),  [1, 4], 'L-shape'; ...
};

cases_eval     = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evalinv  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evaldiff = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_accuracy = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

for k = 1:size(stripSpecs,1)
    p    = stripSpecs{k,1};
    ends = stripSpecs{k,2};
    m = stripmap(p, ends, opt);

    w    = vertex(m.polygon);
    beta = angle(m.polygon) - 1;

    % Points chosen so the ODE-continuation step of evalinv's inverse map
    % doesn't pass close to a critical point of the map (where the
    % derivative vanishes) -- some nearby candidates (e.g. 0.3+0.2i for the
    % hex6 polygon) make the ODE path diverge to Inf/NaN before Newton
    % polish ever gets a chance, the same class of conditioning issue
    % documented for deinvmap in CPP_PLAN.md 9.1.
    zp = [0.25+0.15i, -0.3+0.4i, -0.1+0.3i, -0.2+0.6i].';
    wp = eval(m, zp);
    cases_eval(end+1) = struct( ...
        'desc',    ['eval / ' stripSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata, 'zp', zp), ...
        'outputs', struct('wp', wp), ...
        'tol',     1e-10); %#ok<AGROW>

    zp_inv = evalinv(m, wp);
    cases_evalinv(end+1) = struct( ...
        'desc',    ['evalinv / ' stripSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata, 'wp', wp), ...
        'outputs', struct('zp', zp_inv), ...
        'tol',     1e-9); %#ok<AGROW>

    fp = evaldiff(m, zp);
    cases_evaldiff(end+1) = struct( ...
        'desc',    ['evaldiff / ' stripSpecs{k,3}], ...
        'inputs',  struct('z', m.prevertex, 'beta', beta, 'c', m.constant, 'zp', zp), ...
        'outputs', struct('fp', fp), ...
        'tol',     1e-10); %#ok<AGROW>

    acc = accuracy(m);
    cases_accuracy(end+1) = struct( ...
        'desc',    ['accuracy / ' stripSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata), ...
        'outputs', struct('acc', acc), ...
        'tol',     1e-9); %#ok<AGROW>
end

save(fullfile(outDir, 'stripmap_class.mat'), ...
    'cases_eval', 'cases_evalinv', 'cases_evaldiff', 'cases_accuracy');
fprintf('  stripmap_class: eval=%d evalinv=%d evaldiff=%d accuracy=%d\n', ...
    numel(cases_eval), numel(cases_evalinv), numel(cases_evaldiff), numel(cases_accuracy));
end
