function gen_scqdata(outDir)
%GEN_SCQDATA  Golden values for sctool.scqdata(beta, nqpts).

cases = struct('desc', {}, 'inputs', {}, 'outputs', {}, 'tol', {});

specs = { ...
    [0.5, 0.5, 0.5, 0.5],              8,  'square beta, nqpts=8'; ...
    [0.5, 0.5, 1.5, 0.5, 0.5, 0.5],   8,  'L-shape beta (reentrant), nqpts=8'; ...
    [1/3, 1/3, 1/3],                   8,  'equilateral triangle, nqpts=8'; ...
    [0.5, 0.5, 0.5, 0.5],             12,  'square beta, nqpts=12'; ...
    [0.5, 0.5, 0.5, 0.5],              4,  'square beta, nqpts=4'; ...
    [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],   8,  'hexagon beta, nqpts=8'; ...
};

for k = 1:size(specs, 1)
    beta  = specs{k,1}(:);
    nqpts = specs{k,2};
    qdat  = sctool.scqdata(beta, nqpts);
    cases(end+1) = struct( ...
        'desc',    specs{k,3}, ...
        'inputs',  struct('beta', beta, 'nqpts', nqpts), ...
        'outputs', struct('qdat', qdat), ...
        'tol',     1e-14); %#ok<AGROW>
end

save(fullfile(outDir, 'scqdata.mat'), 'cases');
fprintf('  scqdata: %d cases\n', numel(cases));
end
