function gen_nesolve(outDir)
%GEN_NESOLVE  Golden values for sctool.nesolve and its support routines:
%   neqrdcmp, nechdcmp, nefdjac, nemodel, nelnsrch, nehook, nesolve.

import sctool.*

cases_neqrdcmp = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_nechdcmp = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_nefdjac  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_nesolve  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

% --- neqrdcmp ---
% neqrdcmp is "designed for square matrices only" (see its docstring).
% Matrices to QR-decompose (Householder, encoded as rotation angles)
Aspecs = { ...
    eye(3),                            'identity 3x3'; ...
    [4 3 1; 6 3 -2; -1 2 5],            'general 3x3'; ...
    hilb(4),                           'Hilbert 4x4 (ill-conditioned)'; ...
    % Diagonally-dominant 5x5 (well-conditioned, cond ~3.4) -- an earlier
    % fixture built from sequential integers 1:25 was rank ~2 and made
    % eta (the pivot scale in neqrdcmp.m) underflow to ~1e-16 at the last
    % two columns, so tiny rounding differences between platforms blew up
    % into O(1) divergence. Avoid that here.
    [5 1 0 2 1; 1 6 2 0 1; 0 1 7 1 2; 2 0 1 8 1; 1 1 1 1 9], '5x5 diagonally dominant'; ...
};

for k = 1:size(Aspecs, 1)
    A = Aspecs{k,1};
    [M, M1, M2, sing] = sctool.neqrdcmp(A);
    cases_neqrdcmp(end+1) = struct( ...
        'desc',    Aspecs{k,2}, ...
        'inputs',  struct('A', A), ...
        'outputs', struct('M', M, 'M1', M1, 'M2', M2, 'sing', sing), ...
        'tol',     1e-12); %#ok<AGROW>
end

% --- nechdcmp ---
Hspecs = { ...
    eye(3) * 4,                          'scaled identity (PD)'; ...
    [4 2 1; 2 5 2; 1 2 6],              'SPD 3x3'; ...
    [-1 0; 0 4],                         'indefinite (triggers augmentation)'; ...
    diag([1e-14, 1, 1]),                 'near-singular PD'; ...
};
% Real call sites (nehook.m, nemodel.m) always pass maxoffl=0 (H is known
% to be positive definite, or assumed so); the maxoffl~=0 branch of
% nechdcmp.m references an undefined variable (minl2) and is effectively
% dead code, so we don't exercise it here.
maxoffl = 0;
for k = 1:size(Hspecs, 1)
    H = Hspecs{k,1};
    [L, mu] = sctool.nechdcmp(H, maxoffl);
    cases_nechdcmp(end+1) = struct( ...
        'desc',    Hspecs{k,2}, ...
        'inputs',  struct('H', H, 'maxoffl', maxoffl), ...
        'outputs', struct('L', L, 'mu', mu), ...
        'tol',     1e-12); %#ok<AGROW>
end

% --- nefdjac ---
% Simple 2D system with known analytic Jacobian
fvec = @(x) [x(1)^2 + x(2) - 2; x(1) - x(2)^2 + 1];
xpts = {[1; 1], [0.5; 1.2], [-0.3; 0.8]};
Sx   = ones(2,1);
details = zeros(16,1);
for k = 1:numel(xpts)
    x0 = xpts{k};
    F0 = fvec(x0);
    [J, ~] = sctool.nefdjac(fvec, F0, x0, Sx, details, 0);
    cases_nefdjac(end+1) = struct( ...
        'desc',    sprintf('nefdjac 2D system at [%.2g; %.2g]', x0(1), x0(2)), ...
        'inputs',  struct('x', x0, 'F', F0), ...
        'outputs', struct('J', J), ...
        'tol',     1e-6); %#ok<AGROW>
end

% --- nesolve (full) ---
% System 1: simple 2-variable quadratic, known solution
f2d   = @(x) [x(1)^2 - 1; x(2)^2 - 4];
x0_2d = [2; 3];
det2  = zeros(16,1); det2(2) = 2; det2(8) = 1e-10;  % hook-step, tight tol
[xf, tc] = sctool.nesolve(f2d, x0_2d, det2);
cases_nesolve(end+1) = struct( ...
    'desc',    'nesolve / 2D quadratic x^2=1, y^2=4, hook step', ...
    'inputs',  struct('x0', x0_2d, 'system', '2d', 'details', det2), ...
    'outputs', struct('xf', xf, 'termcode', tc), ...
    'tol',     1e-10); %#ok<AGROW>

% System 2: same system, line search
det_ls = zeros(16,1); det_ls(2) = 1; det_ls(8) = 1e-10;
[xf2, tc2] = sctool.nesolve(f2d, x0_2d, det_ls);
cases_nesolve(end+1) = struct( ...
    'desc',    'nesolve / 2D quadratic x^2=1, y^2=4, line search', ...
    'inputs',  struct('x0', x0_2d, 'system', '2d', 'details', det_ls), ...
    'outputs', struct('xf', xf2, 'termcode', tc2), ...
    'tol',     1e-10); %#ok<AGROW>

% System 3: 3D system
f3d   = @(x) [x(1) + x(2) - 1; x(2) + x(3) - 2; x(1)*x(3) - 0.5];
x0_3d = [0.5; 0.5; 1.5];
det3  = zeros(16,1); det3(2) = 2; det3(8) = 1e-10;
[xf3, tc3] = sctool.nesolve(f3d, x0_3d, det3);
cases_nesolve(end+1) = struct( ...
    'desc',    'nesolve / 3D coupled system', ...
    'inputs',  struct('x0', x0_3d, 'system', '3d', 'details', det3), ...
    'outputs', struct('xf', xf3, 'termcode', tc3), ...
    'tol',     1e-10); %#ok<AGROW>

save(fullfile(outDir, 'nesolve.mat'), ...
    'cases_neqrdcmp', 'cases_nechdcmp', 'cases_nefdjac', 'cases_nesolve');
fprintf('  nesolve: neqrdcmp=%d nechdcmp=%d nefdjac=%d nesolve=%d\n', ...
    numel(cases_neqrdcmp), numel(cases_nechdcmp), numel(cases_nefdjac), numel(cases_nesolve));
end
