function gen_diskmap_class(outDir)
%GEN_DISKMAP_CLASS  Golden values for the @diskmap class-level methods:
%   eval, evalinv, evaldiff, accuracy.

opt = sctool.scmapopt('trace', 0, 'tol', 1e-12);

polys = { ...
    polygon([0, 1, 1+1i, 1i]),             'square'; ...
    polygon([0, 2, 2+1i, 1+1i, 1+2i, 2i]), 'L-shape'; ...
};

cases_eval     = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evalinv  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evaldiff = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_accuracy = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

for k = 1:size(polys,1)
    p = polys{k,1};
    m = diskmap(p, opt);

    w    = vertex(m.polygon);
    beta = angle(m.polygon) - 1;

    zp = [0.1+0.2i, -0.3+0.15i, 0.05-0.4i, 0+0i].';
    wp = eval(m, zp);
    cases_eval(end+1) = struct( ...
        'desc',    ['eval / ' polys{k,2}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata, 'zp', zp), ...
        'outputs', struct('wp', wp), ...
        'tol',     1e-10); %#ok<AGROW>

    zp_inv = evalinv(m, wp);
    cases_evalinv(end+1) = struct( ...
        'desc',    ['evalinv / ' polys{k,2}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata, 'wp', wp), ...
        'outputs', struct('zp', zp_inv), ...
        'tol',     1e-9); %#ok<AGROW>

    fp = evaldiff(m, zp);
    cases_evaldiff(end+1) = struct( ...
        'desc',    ['evaldiff / ' polys{k,2}], ...
        'inputs',  struct('z', m.prevertex, 'beta', beta, 'c', m.constant, 'zp', zp), ...
        'outputs', struct('fp', fp), ...
        'tol',     1e-10); %#ok<AGROW>

    acc = accuracy(m);
    cases_accuracy(end+1) = struct( ...
        'desc',    ['accuracy / ' polys{k,2}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', m.prevertex, 'c', m.constant, 'qdat', m.qdata), ...
        'outputs', struct('acc', acc), ...
        'tol',     1e-9); %#ok<AGROW>
end

save(fullfile(outDir, 'diskmap_class.mat'), ...
    'cases_eval', 'cases_evalinv', 'cases_evaldiff', 'cases_accuracy');
fprintf('  diskmap_class: eval=%d evalinv=%d evaldiff=%d accuracy=%d\n', ...
    numel(cases_eval), numel(cases_evalinv), numel(cases_evaldiff), numel(cases_accuracy));
end
