function gen_stripmap_private(outDir)
%GEN_STRIPMAP_PRIVATE  Golden values for @stripmap/private functions:
%   stparam, stquad, stderiv, stmap, stinvmap.
%
%   Uses bounded polygons (no vertices at infinity), matching the
%   convention in tests/testStrip.m's fixtures — this avoids the
%   complications of supplying explicit interior angles for unbounded
%   polygons (POLYGON requires ALPHA to be given manually whenever any
%   vertex is Inf). Signatures (see @stripmap/private):
%     stparam(w,beta,ends,z0,options) -> [z,c,qdat]
%     stquad(z1,z2,sing1,z,beta,qdat) -> I
%     stderiv(zp,z,beta,c,j)          -> fprime   (j optional vertex index)
%     stmap(zp,w,beta,z,c,qdat)       -> wp        (note: w precedes z)
%     stinvmap(wp,w,beta,z,c,qdat)    -> zp

opt = sctool.scmapopt('trace', 0, 'tol', 1e-12);

stripSpecs = { ...
    polygon([4, 2i, -2+4i, -3, -3-1i, 2-2i]), [1, 4], 'hex6'; ...
    polygon([1i, -1+1i, -1-1i, 1-1i, 1, 0]),  [1, 4], 'L-shape'; ...
};

cases_stparam  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_stquad   = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_stderiv  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_stmap    = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_stinvmap = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

for k = 1:size(stripSpecs,1)
    p    = stripSpecs{k,1};
    ends = stripSpecs{k,2};
    w    = vertex(p);
    beta = angle(p) - 1;

    [w2, beta2, ends2] = scfix('st', w, beta, ends);
    [z, c, qdat] = stripmap.private_('stparam', w2, beta2, ends2, [], opt);

    cases_stparam(end+1) = struct( ...
        'desc',    ['stparam / ' stripSpecs{k,3}], ...
        'inputs',  struct('w', w2, 'beta', beta2, 'ends', ends2), ...
        'outputs', struct('z', z, 'c', c, 'qdat', qdat), ...
        'tol',     1e-10); %#ok<AGROW>

    % stquad: integrate from a finite singular prevertex to a nearby point
    finIdx = find(~isinf(z));
    if numel(finIdx) >= 1
        za = z(finIdx(1)); zb = za + 0.3 + 0.2i;
        I  = stripmap.private_('stquad', za, zb, finIdx(1), z, beta2, qdat);
        cases_stquad(end+1) = struct( ...
            'desc',    ['stquad / ' stripSpecs{k,3}], ...
            'inputs',  struct('z1',za,'z2',zb,'sing1',finIdx(1),'z',z,'beta',beta2,'qdat',qdat), ...
            'outputs', struct('I', I), ...
            'tol',     1e-11); %#ok<AGROW>
    end

    % stderiv and stmap
    zp = [0.2+0.3i, -0.4+0.5i].';
    fp = stripmap.private_('stderiv', zp, z, beta2, c);
    wp = stripmap.private_('stmap', zp, w2, beta2, z, c, qdat);
    cases_stderiv(end+1) = struct( ...
        'desc',    ['stderiv / ' stripSpecs{k,3}], ...
        'inputs',  struct('zp', zp, 'z', z, 'beta', beta2, 'c', c), ...
        'outputs', struct('fp', fp), ...
        'tol',     1e-11); %#ok<AGROW>
    cases_stmap(end+1) = struct( ...
        'desc',    ['stmap / ' stripSpecs{k,3}], ...
        'inputs',  struct('zp', zp, 'w', w2, 'beta', beta2, 'z', z, 'c', c, 'qdat', qdat), ...
        'outputs', struct('wp', wp), ...
        'tol',     1e-11); %#ok<AGROW>

    % stinvmap
    zp_inv = stripmap.private_('stinvmap', wp, w2, beta2, z, c, qdat);
    cases_stinvmap(end+1) = struct( ...
        'desc',    ['stinvmap / ' stripSpecs{k,3}], ...
        'inputs',  struct('wp', wp, 'w', w2, 'beta', beta2, 'z', z, 'c', c, 'qdat', qdat), ...
        'outputs', struct('zp', zp_inv), ...
        'tol',     1e-10); %#ok<AGROW>
end

save(fullfile(outDir, 'stripmap_private.mat'), ...
    'cases_stparam', 'cases_stquad', 'cases_stderiv', 'cases_stmap', 'cases_stinvmap');
fprintf('  stripmap_private: stparam=%d stquad=%d stderiv=%d stmap=%d stinvmap=%d\n', ...
    numel(cases_stparam), numel(cases_stquad), numel(cases_stderiv), ...
    numel(cases_stmap), numel(cases_stinvmap));
end
