function gen_moebius(outDir)
%GEN_MOEBIUS  Golden values for the @moebius class.
%
%   Five groups:
%     cases_construct  three-point constructor (z,w), including infinities
%     cases_eval       eval and diff at points (including Inf, and points
%                      whose image is Inf)
%     cases_ops        inv, normal, unary minus, and the scalar arithmetic
%                      operators (+ - * / and scalar/map)
%     cases_invpoints  inv() of a three-point map, which must swap the
%                      stored source and image triples as well
%     cases_compose    M1(M2) composition
%
%   Coefficients are stored as the 4-vector [c1 c2 c3 c4] of
%   (c1 + c2*z)/(c3 + c4*z), i.e. exactly double(M).

cases_construct = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_eval      = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_ops       = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_compose   = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_invpoints = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

% ---------------------------------------------------------------- construct
% Every branch of moebius.m's (Z,W) constructor: all finite; Inf in w at
% each of the three slots; Inf in z at each slot; and the combined cases
% where both z and w have an infinity (which is what selects the special
% A(1)-assignment branch).
specs = { ...
    [0, 1, 1i],        [1, -1, 1i],       'all finite'; ...
    [0, 1, 1i],        [2+1i, 3, -1i],    'all finite, asymmetric'; ...
    [-1, 0, 1],        [Inf, 0, 1],       'w(1) = Inf'; ...
    [-1, 0, 1],        [0, Inf, 1],       'w(2) = Inf'; ...
    [-1, 0, 1],        [0, 1, Inf],       'w(3) = Inf'; ...
    [Inf, 0, 1],       [-1, 0, 1],        'z(1) = Inf'; ...
    [0, Inf, 1],       [-1, 0, 1],        'z(2) = Inf'; ...
    [0, 1, Inf],       [-1, 0, 1],        'z(3) = Inf'; ...
    [Inf, 0, 1],       [0, Inf, 1],       'z(1) = Inf and w(2) = Inf'; ...
    [0, Inf, 1],       [Inf, 0, 1],       'z(2) = Inf and w(1) = Inf'; ...
    [0, 1, Inf],       [0, Inf, 1],       'z(3) = Inf and w(2) = Inf'; ...
    [Inf, 1i, -1i],    [2, Inf, 0],       'z(1) = Inf and w(2) = Inf, complex'; ...
    [1i, -1i, Inf],    [0, 3-1i, Inf],    'z(3) = Inf and w(3) = Inf'; ...
};

for k = 1:size(specs,1)
    z = specs{k,1}(:);
    w = specs{k,2}(:);
    M = moebius(z, w);
    S = struct(M);
    cases_construct(end+1) = struct( ...
        'desc',    ['construct / ' specs{k,3}], ...
        'inputs',  struct('z', z, 'w', w), ...
        'outputs', struct('coeff', double(M).', 'source', S.source(:), 'image', S.image(:)), ...
        'tol',     1e-12); %#ok<AGROW>
end

% --------------------------------------------------------------------- eval
% zp deliberately includes Inf and the pole of each map, so the Inf-handling
% and the |den| < 3*eps -> Inf rule in eval.m are both exercised.
evalspecs = { ...
    [1, 2, 3, 4],          [0; 1; -0.75; 1i; Inf],        'generic map'; ...
    [1, 0, 0, 1],          [0; 2; -3i; Inf],              '1/z (pole at 0)'; ...
    [0, 1, 1, 0],          [0; 2; -3i; Inf],              'z/1 reversed: (0+z)/(1+0z)'; ...
    [2+1i, -1, 3, 1i],     [0; 1+1i; 3i; Inf],            'complex coefficients'; ...
    [1, 2, 0, 1],          [0; -1; 2; Inf],               'pole at 0 (c3 = 0)'; ...
};

for k = 1:size(evalspecs,1)
    C  = evalspecs{k,1}(:).';
    zp = evalspecs{k,2}(:);
    M  = moebius(C);
    fp = eval(M, zp);
    d  = diff(M);
    dp = d(zp);
    cases_eval(end+1) = struct( ...
        'desc',    ['eval / ' evalspecs{k,3}], ...
        'inputs',  struct('coeff', C(:), 'zp', zp), ...
        'outputs', struct('fp', fp, 'dp', dp), ...
        'tol',     1e-12); %#ok<AGROW>
end

% Also evaluate a three-point map at its own source points: the images must
% come back exactly (this is the defining property of the constructor).
for k = 1:size(specs,1)
    z = specs{k,1}(:);
    w = specs{k,2}(:);
    M = moebius(z, w);
    S = struct(M);
    zp = S.source(:);
    fp = eval(M, zp);
    d  = diff(M);
    dp = d(zp);
    cases_eval(end+1) = struct( ...
        'desc',    ['eval at source points / ' specs{k,3}], ...
        'inputs',  struct('coeff', double(M).', 'zp', zp), ...
        'outputs', struct('fp', fp, 'dp', dp), ...
        'tol',     1e-12); %#ok<AGROW>
end

% ---------------------------------------------------------------------- ops
opspecs = { ...
    [1, 2, 3, 4],        2,          'generic map, real scalar'; ...
    [1, 2, 3, 4],        -1.5+0.5i,  'generic map, complex scalar'; ...
    [2+1i, -1, 3, 1i],   0.25i,      'complex coefficients'; ...
    [1, 0, 0, 1],        3,          '1/z'; ...
    [1, 2, 0, 1],        -2,         'zero constant term in denominator'; ...
};

for k = 1:size(opspecs,1)
    C = opspecs{k,1}(:).';
    s = opspecs{k,2};
    M = moebius(C);
    cases_ops(end+1) = struct( ...
        'desc',    ['ops / ' opspecs{k,3}], ...
        'inputs',  struct('coeff', C(:), 's', s), ...
        'outputs', struct( ...
            'coeff_inv',    double(inv(M)).', ...
            'coeff_normal', double(normal(M)).', ...
            'coeff_neg',    double(-M).', ...
            'coeff_plus',   double(M + s).', ...
            'coeff_minus',  double(M - s).', ...
            'coeff_times',  double(M * s).', ...
            'coeff_rdiv',   double(M / s).', ...
            'coeff_ldiv',   double(s / M).'), ...
        'tol',     1e-12); %#ok<AGROW>
end

% inv() of a three-point map must also swap the stored source/image.
invspecs = { ...
    [0, 1, 1i],  [Inf, 0, 1],  'three-point with Inf in w'; ...
    [0, 1, 1i],  [1, -1, 1i],  'three-point all finite'; ...
    [Inf, 0, 1], [-1, 0, 1],   'three-point with Inf in z'; ...
};
for k = 1:size(invspecs,1)
    z = invspecs{k,1}(:);
    w = invspecs{k,2}(:);
    Mi = inv(moebius(z, w));
    Si = struct(Mi);
    cases_invpoints(end+1) = struct( ...
        'desc',    ['inv swaps source and image / ' invspecs{k,3}], ...
        'inputs',  struct('z', z, 'w', w), ...
        'outputs', struct('coeff_inv', double(Mi).', 'source_inv', Si.source(:), ...
                          'image_inv', Si.image(:)), ...
        'tol',     1e-12); %#ok<AGROW>
end

% ------------------------------------------------------------------ compose
composespecs = { ...
    [1, 2, 3, 4],       [0, 1, 1, 0],        'generic composed with 1/z'; ...
    [2+1i, -1, 3, 1i],  [1, -1i, 2, 1],      'complex composed with complex'; ...
    [1, 0, 0, 1],       [1, 0, 0, 1],        '1/z composed with itself (identity)'; ...
};

for k = 1:size(composespecs,1)
    C1 = composespecs{k,1}(:).';
    C2 = composespecs{k,2}(:).';
    M1 = moebius(C1);
    M2 = moebius(C2);
    M  = M1(M2);
    zp = [0.3; -1.2+0.4i; 2i; Inf];
    cases_compose(end+1) = struct( ...
        'desc',    ['compose / ' composespecs{k,3}], ...
        'inputs',  struct('coeff1', C1(:), 'coeff2', C2(:), 'zp', zp), ...
        'outputs', struct('coeff', double(M).', 'fp', eval(M, zp)), ...
        'tol',     1e-12); %#ok<AGROW>
end

save(fullfile(outDir, 'moebius.mat'), ...
    'cases_construct', 'cases_eval', 'cases_ops', 'cases_invpoints', 'cases_compose');
fprintf('  moebius: construct=%d eval=%d ops=%d invpoints=%d compose=%d\n', ...
    numel(cases_construct), numel(cases_eval), numel(cases_ops), ...
    numel(cases_invpoints), numel(cases_compose));
end
