function gen_hplmap_private(outDir)
%GEN_HPLMAP_PRIVATE  Golden values for @hplmap/private functions:
%   hpparam, hpquad, hpderiv, hpmap, hpinvmap.

opt = sctool.scmapopt('trace', 0, 'tol', 1e-12);

polys = { ...
    polygon([0, 1, 1+1i, 1i]),             'square'; ...
    polygon([0, 2, 2+1i, 1+1i, 1+2i, 2i]), 'L-shape'; ...
};

cases_hpparam  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_hpquad   = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_hpderiv  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_hpmap    = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_hpinvmap = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

for k = 1:size(polys,1)
    p    = polys{k,1};
    w    = vertex(p); beta = angle(p) - 1;
    [w2, beta2] = scfix('hp', w, beta);
    [z, c, qdat] = hplmap.private_('hpparam', w2, beta2, [], opt);

    cases_hpparam(end+1) = struct( ...
        'desc',    ['hpparam / ' polys{k,2}], ...
        'inputs',  struct('w', w2, 'beta', beta2), ...
        'outputs', struct('z', z, 'c', c, 'qdat', qdat), ...
        'tol',     1e-10); %#ok<AGROW>

    % hpquad: finite prevertices on real line; sing->interior. hpquad
    % expects only the finite singularities (z(1:end-1), beta(1:end-1)),
    % since z(end)=Inf is the prevertex of the half-plane's point at
    % infinity and is excluded from the quadrature.
    zfin = z(~isinf(z)); betafin = beta2(~isinf(z));
    finIdx = find(~isinf(z));
    if numel(finIdx) >= 2
        za = zfin(1); zb = mean(zfin(1:2)) + 0.5i;
        I = hplmap.private_('hpquad', za, zb, 1, zfin, betafin, qdat);
        cases_hpquad(end+1) = struct( ...
            'desc',    ['hpquad sing->interior / ' polys{k,2}], ...
            'inputs',  struct('z1',za,'z2',zb,'sing1',1,'z',zfin,'beta',betafin,'qdat',qdat), ...
            'outputs', struct('I', I), ...
            'tol',     1e-11); %#ok<AGROW>
    end

    % hpderiv
    zp = [0.5+1i, -0.2+2i, 1.5+0.8i].';
    fp = hplmap.private_('hpderiv', zp, z, beta2, c);
    cases_hpderiv(end+1) = struct( ...
        'desc',    ['hpderiv / ' polys{k,2}], ...
        'inputs',  struct('zp', zp, 'z', z, 'beta', beta2, 'c', c), ...
        'outputs', struct('fp', fp), ...
        'tol',     1e-11); %#ok<AGROW>

    % hpmap
    wp = hplmap.private_('hpmap', zp, w2, beta2, z, c, qdat);
    cases_hpmap(end+1) = struct( ...
        'desc',    ['hpmap / ' polys{k,2}], ...
        'inputs',  struct('zp', zp, 'w', w2, 'beta', beta2, 'z', z, 'c', c, 'qdat', qdat), ...
        'outputs', struct('wp', wp), ...
        'tol',     1e-11); %#ok<AGROW>

    % hpinvmap
    zp_inv = hplmap.private_('hpinvmap', wp, w2, beta2, z, c, qdat);
    cases_hpinvmap(end+1) = struct( ...
        'desc',    ['hpinvmap / ' polys{k,2}], ...
        'inputs',  struct('wp', wp, 'w', w2, 'beta', beta2, 'z', z, 'c', c, 'qdat', qdat), ...
        'outputs', struct('zp', zp_inv), ...
        'tol',     1e-10); %#ok<AGROW>
end

save(fullfile(outDir, 'hplmap_private.mat'), ...
    'cases_hpparam', 'cases_hpquad', 'cases_hpderiv', 'cases_hpmap', 'cases_hpinvmap');
fprintf('  hplmap_private: hpparam=%d hpquad=%d hpderiv=%d hpmap=%d hpinvmap=%d\n', ...
    numel(cases_hpparam), numel(cases_hpquad), numel(cases_hpderiv), ...
    numel(cases_hpmap), numel(cases_hpinvmap));
end
