function gen_rectmap_class(outDir)
%GEN_RECTMAP_CLASS  Golden values for the @rectmap class-level methods:
%   eval, evalinv, evaldiff, accuracy, corners.

opt = sctool.scmapopt('trace', 0, 'tol', 1e-9);

rectSpecs = { ...
    polygon([4, 2i, -2+4i, -3, -3-1i, 2-2i]), 1:4,      'hex6 / corners 1234'; ...
    polygon([1i, -1+1i, -1-1i, 1-1i, 1, 0]),  [2,4,5,1], 'L-shape / corners 2451'; ...
};

cases_eval     = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evalinv  = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_evaldiff = struct('desc',{},'inputs',{},'outputs',{},'tol',{});
cases_accuracy = struct('desc',{},'inputs',{},'outputs',{},'tol',{});

for k = 1:size(rectSpecs,1)
    p       = rectSpecs{k,1};
    corners = rectSpecs{k,2};
    m = rectmap(p, corners, opt);

    w    = vertex(m.polygon);
    beta = angle(m.polygon) - 1;
    z    = m.prevertex;
    K  = max(real(z));
    Kp = max(imag(z));

    % rectmap.m's constructor stores `m.polygon` AFTER applying scfix to
    % (w,beta,corner) -- same as the rparam generator fix (CPP_PLAN.md
    % 9.5): the ORIGINAL pre-scfix `corners` local variable doesn't match
    % the post-scfix w/beta stored here, so a fresh RectMap built from
    % THIS w/beta needs the POST-scfix corners, not the original ones.
    [~, ~, corners_post] = scfix('r', vertex(p), angle(p) - 1, corners);

    zp = [K/4 + Kp/4*1i, K*3/4 + Kp/2*1i].';
    wp = eval(m, zp);
    cases_eval(end+1) = struct( ...
        'desc',    ['eval / ' rectSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', z, 'c', m.constant, 'L', m.stripL, 'qdat', m.qdata, ...
                           'zp', zp, 'corners', corners_post), ...
        'outputs', struct('wp', wp), ...
        'tol',     1e-8); %#ok<AGROW>

    zp_inv = evalinv(m, wp);
    cases_evalinv(end+1) = struct( ...
        'desc',    ['evalinv / ' rectSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', z, 'c', m.constant, 'L', m.stripL, 'qdat', m.qdata, ...
                           'wp', wp, 'corners', corners_post), ...
        'outputs', struct('zp', zp_inv), ...
        'tol',     1e-7); %#ok<AGROW>

    fp = evaldiff(m, zp);
    cases_evaldiff(end+1) = struct( ...
        'desc',    ['evaldiff / ' rectSpecs{k,3}], ...
        'inputs',  struct('z', z, 'beta', beta, 'c', m.constant, 'L', m.stripL, 'zp', zp), ...
        'outputs', struct('fp', fp), ...
        'tol',     1e-8); %#ok<AGROW>

    acc = accuracy(m);
    cases_accuracy(end+1) = struct( ...
        'desc',    ['accuracy / ' rectSpecs{k,3}], ...
        'inputs',  struct('w', w, 'beta', beta, 'z', z, 'c', m.constant, 'L', m.stripL, 'qdat', m.qdata, ...
                           'corners', corners_post), ...
        'outputs', struct('acc', acc), ...
        'tol',     1e-7); %#ok<AGROW>
end

save(fullfile(outDir, 'rectmap_class.mat'), ...
    'cases_eval', 'cases_evalinv', 'cases_evaldiff', 'cases_accuracy');
fprintf('  rectmap_class: eval=%d evalinv=%d evaldiff=%d accuracy=%d\n', ...
    numel(cases_eval), numel(cases_evalinv), numel(cases_evaldiff), numel(cases_accuracy));
end
