#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "golden_reader.hpp"
#include "sctoolbox/nefdjac.hpp"

TEST_CASE("nefdjac matches MATLAB goldens") {
    auto groups = golden::loadGoldens(std::string(GOLDENS_TEXT_DIR) + "/nesolve.gold");
    auto& cases = groups.at("cases_nefdjac");
    REQUIRE(!cases.empty());

    // Same setup as gen_nesolve.m / testCppGoldens.m's testNefdjac: the
    // golden was generated by calling nefdjac with a raw details=zeros(16,1)
    // (not run through neinck), so details(13) (eta) is 0 and the resulting
    // Jacobian is NaN-filled by construction -- this is intentional, not a
    // bug to work around.
    sctoolbox::Fvec fvec = [](const Eigen::VectorXd& x) {
        Eigen::VectorXd f(2);
        f(0) = x(0) * x(0) + x(1) - 2.0;
        f(1) = x(0) - x(1) * x(1) + 1.0;
        return f;
    };
    Eigen::VectorXd sx = Eigen::VectorXd::Ones(2);
    Eigen::VectorXd details = Eigen::VectorXd::Zero(16);

    for (const auto& c : cases) {
        const auto& xin = c.in("x");
        const auto& Fin = c.in("F");
        Eigen::VectorXd x(2), F(2);
        x(0) = xin(0, 0).real();
        x(1) = xin(1, 0).real();
        F(0) = Fin(0, 0).real();
        F(1) = Fin(1, 0).real();

        int nofun = 0;
        Eigen::MatrixXd J = sctoolbox::nefdjac(fvec, F, x, sx, details, nofun);

        const auto& Jg = c.out("J");
        for (int i = 0; i < 2; ++i) {
            for (int j = 0; j < 2; ++j) {
                const double expected = Jg(i, j).real();
                if (!std::isfinite(expected)) {
                    // This golden case divides by an exactly-zero step size
                    // by construction (details(13)=0 bypassing neinck), so
                    // the numerator is "supposed" to be exactly 0 too -- but
                    // whether it actually is can depend on the last bit of
                    // x(j)^2 (MATLAB's `^` vs C++'s `*`), tipping the result
                    // between NaN (0/0) and Inf (tiny/0). Both are correct
                    // reproductions of the degenerate behavior being tested.
                    CHECK(!std::isfinite(J(i, j)));
                } else {
                    CHECK(std::abs(J(i, j) - expected) < c.tol);
                }
            }
        }
    }
}
